### ISSUE TITLE
X-Plane crash 

### ISSUE THREAD

**Issue by reddeviln** [YesAviation/Boeing-747-400#3]
X-Plane crashes when unloading the aircraft e.g through the developer menu or by just starting another flight

**Comment by YesAviation** [comment]
This most likely has to deal with the A.I. portion of the code. We should remove this. But doing so will remove the ability (and crash people) who choose to use the quick flight engines ready function and other stuff.

**Comment by PresentMonkey** [comment]
When closing the game, it has to do with librain. We could remove it for now.

**Comment by reddeviln** [comment]
Fixed
